# Generated by Django 3.2.5 on 2022-05-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='歌曲id')),
                ('title', models.CharField(max_length=100, verbose_name='歌曲名称')),
                ('author', models.CharField(max_length=100, verbose_name='歌手')),
                ('lrc', models.TextField(verbose_name='歌词')),
                ('url', models.URLField(max_length=250, verbose_name='歌曲播放链接')),
                ('pic', models.URLField(max_length=100, verbose_name='图片链接')),
            ],
            options={
                'db_table': 'song',
            },
        ),
        migrations.CreateModel(
            name='Toplist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='排名')),
                ('category', models.SmallIntegerField(choices=[(1, '飙升榜'), (2, '新歌榜'), (3, '原创榜'), (4, '热歌榜')], verbose_name='排行榜类别')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toplist', to='song.song')),
            ],
            options={
                'db_table': 'toplist',
            },
        ),
    ]
